service: backend-hello-build-tech-test
frameworkVersion: '3'
custom: ${file(./env/${opt:stage, 'dev'}.yml)}

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: ${self:custom.profile}
  timeout: 30
  stage: ${self:custom.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [DynamoDBUsersTable, Arn]
  environment:
    CORS_ORIGIN: ${self:custom.allow_origin}
    GITHUB_GRAPHQL_API_URL: ${self:custom.github_graphql_api_url}
    GITHUB_GRAPHQL_API_TOKEN: ${self:custom.github_graphql_api_token}
    USER_TABLE: ${self:custom.user_table}

resources: 
  Resources:
    DynamoDBUsersTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "user-table"
        AttributeDefinitions:
          - AttributeName: Email
            AttributeType: S
          - AttributeName: Username
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: Email
            KeyType: HASH
          - AttributeName: Username
            KeyType: RANGE
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: cognito-user-pool
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireNumbers: true
            RequireSymbols: true


    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: user-pool-ui
        GenerateSecret: False
        UserPoolId: { Ref: CognitoUserPool }
        AccessTokenValidity: 5
        IdTokenValidity: 5
        ExplicitAuthFlows:
          - "ADMIN_NO_SRP_AUTH"

functions:
  users:
    handler: functions/users/handler.users
    events:
      - http:
          path: /v1/users/{proxy+}
          method: ANY
          cors:
            origin:
              - ${self:custom.allow_origin}
            headers:
              - "*"
            allowCredentials: false
            cacheControl: "max-age=600, s-maxage=600, proxy-revalidate"
